TestModel/urls.py
from django.conf.urls import url
from . import views,addtest_req

app_name = 'TestM'  # 关键是这行
urlpatterns = [
    url(r'^addtest/$', addtest_req.addtest_post),
    url(r'^(?P<question_id>[0-9]+)/detail/$', views.index, name='detail'),
]

untitled2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import *

from . import views,testdb,search,searchpost
from TestModel import addtest_req


urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r'^$', views.hello),
    url(r'^hello$', views.hello),
    url(r'^testdb$', testdb.testdb),
    url(r'^search-form$', search.search_form),
    url(r'^search$', search.search),
    url(r'^search-post$', searchpost.search_post),
    #url(r'^addtest$', addtest_req.addtest_post),
    url(r'^TestM/', include('TestModel.urls')),
]

TestModel/models.py
from django.db import models

# Create your models here.
class Test(models.Model):
    name = models.CharField(max_length=20)
    password = models.IntegerField(default='0')


class User(models.Model):
    name = models.CharField('姓名',max_length=20)
    password = models.CharField('密码',max_length=16)
    age = models.IntegerField()

class User2(models.Model):
    name = models.CharField('姓名',max_length=20)
    password = models.CharField('密码',max_length=16)
    age = models.IntegerField()
    class Meta:
        db_table = "User2"

TestModel/views.py
from django.shortcuts import render

# Create your views here.
def index(question,question_id):
    context          = {}
    context['hello'] = 'test---url'
    return render(question, 'TestModel/hello.html', context)

untitled2/views.py
from django.http import HttpResponse
from django.shortcuts import render

def hello(request):
    context          = {}
    context['hello'] = 'Hello World!!!!'
    return render(request, 'hello.html', context)

templates/TestModel/addtest.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>
</head>
<body>
    <form action="/addtest" method="post">
        {% csrf_token %}
        <input type="text" name="name">
        <input type="text" name="password">
        <input type="submit" value="添加">
    </form>

    <p>{{ rlt }}</p>
    <p>{{ rlt3 }}</p>
</body>
</html>

templates/TestModel/hello.html
<html>
<body>
<li><a href="{% url 'TestM:detail' question_id %}">{{ question.question_text }}</a></li>

</body>
</html>

templates/addtest.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title> asfdasgfdsag)</title>
</head>
<body>
    <form action="/addtest" method="post">
        {% csrf_token %}
        <input type="text" name="name">
        <input type="text" name="password">
        <input type="submit" value="添加">
    </form>

    <p>{{ rlt }}</p>
    <p>{{ rlt3 }}</p>
</body>
</html>

templates/hello.html
<h1>{{ hello }}</h1>

templates/post.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>
</head>
<body>
    <form action="/search-post" method="post">
        {% csrf_token %}
        <input type="text" name="q">
        <input type="submit" value="搜索">
    </form>

    <p>{{ rlt }}</p>
</body>
</html>

templates/search_form.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>网站测试(runoob.com)</title>
</head>
<body>
    <form action="/search" method="get">
        <input type="text" name="q">
        <input type="submit" value="搜索">
    </form>
</body>
</html>